CBIIT/ncippe-application

src/main/java/gov/nci/ppe/services/impl/EmailLogServiceImpl.java

1. Removed the code to fetch AWS credentials from properties file
2. Amended the code to build a default AWS Client without credentials
and region.

NCIPPE-302 | Email Notifications are not generated for any user

---

src/main/java/gov/nci/ppe/services/impl/UserServiceImpl.java

Updated content for Withdrawal notifications

NCIPPE-280 Update Links in Notification

---

src/main/java/gov/nci/ppe/data/entity/Participant.java

Updated the Entity field length to 32 to match the database change.

NCIPPE-199 | Generate New Participant Records

---

src/main/java/gov/nci/ppe/configurations/EmailServiceConfig.java
src/main/java/gov/nci/ppe/configurations/NotificationServiceConfig.java
src/main/java/gov/nci/ppe/services/impl/UserServiceImpl.java
src/main/resources/NotificationService.properties

Amended code to send out email and system notification to CRC when a new
patient is inserted into PPE from OPEN

NCIPPE-72 | CRC Added to PPE

---

src/main/java/gov/nci/ppe/controller/UserController.java
src/main/java/gov/nci/ppe/services/impl/UserServiceImpl.java
src/main/java/gov/nci/ppe/util/TimeUtil.java
src/main/resources/application.properties

Added Activation logic to login method

NCIPPE-313 NCIPPE| First time users cannot log into the Portal

---

src/main/java/gov/nci/ppe/services/impl/UserServiceImpl.java

CRC and Provider status will be set to Initiated by default instead of
New.

NCIPPE-135 | Update CRC Provider

---

src/main/resources/NotificationService.properties

Fixed the Notification language

NCIPPE-144 | UX enhancement - notification copy

---

src/main/java/gov/nci/ppe/controller/NotificationController.java

Restored accidentally deleted file

NCIPPE-330 Notifications not being marked as read

---

src/main/java/gov/nci/ppe/configurations/NotificationServiceConfig.java
src/main/java/gov/nci/ppe/services/impl/AmazonS3ServiceImpl.java
src/main/resources/NotificationService.properties

NCIPPE-331 Incorrect notifications raised when Biomarker report uploaded

---

src/main/java/gov/nci/ppe/services/impl/AmazonS3ServiceImpl.java

NCIPP-333 Duplicate notifications for new consent form

---

src/main/java/gov/nci/ppe/constants/PPERole.java
src/main/java/gov/nci/ppe/controller/UserController.java
src/main/java/gov/nci/ppe/data/entity/ContentEditor.java
src/main/java/gov/nci/ppe/data/entity/dto/ContentEditorDTO.java
src/main/java/gov/nci/ppe/services/impl/UserServiceImpl.java

NCIPPE-338 Login as Content Admin

---

src/main/java/gov/nci/ppe/data/entity/Participant.java

Updated to use new FileType code vlues

NCIPP-369 origin/bugfix/NCIPPE-369-ncippe-crc-cannot-upload-consent-form

---

src/main/java/gov/nci/ppe/data/entity/NCORPSite.java
src/main/java/gov/nci/ppe/data/entity/dto/NCORPSiteDTO.java

NCIPPE-493 Create microservice to return list of NCORP sites

---

src/main/java/gov/nci/ppe/services/impl/EmailLogServiceImpl.java
src/main/resources/NotificationService.properties

Updated Email Notifications - Fixed wrong signature for biomarker report email to CRC/Provider
Updated System Notifications - Fixed missing comma for CRC withdrawing Patient.

NCIPPE-423 Update Email and System Notifications

---

src/main/java/gov/nci/ppe/controller/UserController.java
src/main/java/gov/nci/ppe/services/AuthorizationService.java
src/main/java/gov/nci/ppe/services/UserService.java
src/main/java/gov/nci/ppe/services/impl/AuditServiceImpl.java
src/main/java/gov/nci/ppe/services/impl/AuthorizationServiceImpl.java
src/main/java/gov/nci/ppe/services/impl/UserServiceImpl.java

Modified ReST endpoints to match new workflow

NCIPPE-437 Refactor "Add New Participant" workflow and error messages

---

src/test/java/gov/nci/ppe/services/NCORPSiteServiceTest.java

Add Unit Test for NCORPSiteService

NCI-168 JUnit Test Cases

---

pom.xml
src/main/java/gov/nci/ppe/configurations/DozerConfig.java
src/main/java/gov/nci/ppe/controller/NCORPSiteController.java
src/main/java/gov/nci/ppe/controller/PatientReportController.java
src/main/java/gov/nci/ppe/controller/UserController.java
src/main/java/gov/nci/ppe/data/dozer/UserToUserUUIDDozerConverter.java
src/main/java/gov/nci/ppe/data/entity/Participant.java
src/main/java/gov/nci/ppe/data/entity/dto/ParticipantDTO.java
src/main/java/gov/nci/ppe/open/data/entity/dto/OpenRequestDTO.java
src/main/java/gov/nci/ppe/open/data/entity/dto/OpenResponseDTO.java
src/main/java/gov/nci/ppe/open/data/entity/dto/UserEnrollmentDataDTO.java
src/main/java/gov/nci/ppe/services/impl/AmazonS3ServiceImpl.java
src/main/java/gov/nci/ppe/services/impl/AuthorizationServiceImpl.java
src/main/java/gov/nci/ppe/services/impl/UserServiceImpl.java
src/main/resources/dozer-mappings.xml

Updated dozer to 6.5
Added dateOfBirth field to Participant and ParticipantDTO
Save dateOfBirth from OPEN

NCIPPE-361 Minor Turns 17.5

---

src/main/java/gov/nci/ppe/data/entity/NCORPSite.java
src/main/java/gov/nci/ppe/data/entity/dto/NCORPSiteDTO.java

Populate Hospital list with final data provided by client
Add website to JSON output of /publicapi/v1/sites

NCIPPE-444

---

src/test/java/gov/nci/ppe/services/UserServiceTest.java

NCIPPE-399 MUST HAVE: Notification for unread biomarker reports

---

src/main/java/gov/nci/ppe/services/impl/UserServiceImpl.java

Notification to CRC use CRC preferred language instead of patient's

NCIPPE-416 MUST HAVE: Spanish Translations on Portal - Notifications

---

pom.xml
src/main/resources/application.properties

Prep for 2.1, cleanup unused properties

NCIPPE-519 Migrate to AWS Codebuild

---

src/main/java/gov/nci/ppe/controller/PatientReportController.java
src/main/java/gov/nci/ppe/services/AuditService.java
src/main/java/gov/nci/ppe/services/impl/AmazonS3ServiceImpl.java
src/main/java/gov/nci/ppe/services/impl/AuditServiceImpl.java
src/main/java/gov/nci/ppe/services/impl/EmailLogServiceImpl.java
src/main/java/gov/nci/ppe/services/impl/FileServiceImpl.java
src/main/java/gov/nci/ppe/services/impl/NotificationServiceImpl.java
src/main/java/gov/nci/ppe/services/impl/UserServiceImpl.java

NCIPPE-557 Mocha Admin Upload report for Patient in State NEW
